# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Every Vagrant development environment requires a box. You can search for boxes at https://app.vagrantup.com/boxes/search?utf8=%E2%9C%93&sort=downloads&provider=&q=ansible
  config.vm.box = "debian/stretch64"
  config.vm.synced_folder ".", "/vagrant", disabled: false, create: true
  #vagrant plugin install vagrant-disksize
  config.disksize.size = '10GB'
  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     #vb.gui = true
     #Customize the amount of memory on the VM:
     #vb.memory = "256"
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.  
  config.vm.provision "shell", inline: <<-SHELL
     #sudo apt-get update
     #sudo apt-get install -y ansible sshpass snapd vpnc sshuttle dos2unix debian-keyring stoken
     #sudo snap install snapcraft --classic
     #sudo bash -c 'echo deb http://archive.ubuntu.com/ubuntu xenial universe > /etc/apt/sources.list.d/xenial.list'
     #sudo hostname -b usstlat
     #git clone https://github.com/vinayski/home.git home
     #ln -sf home/.profile .profile
     #ln -sf home/.functions .functions
     #sudo do-release-upgrade
     #sudo bash -c 'echo "
#[unix]
#94.35 ansible_ssh_pass='inst' ansible_ssh_user='inst'
# "> ~/inventory'

    SHELL

  config.vm.provision "ansible_local" do |ansible|
    ansible.install = true
    ansible.verbose = true
    ansible.playbook = "playbook.yml"
  end    
end
