---
- name: install basic package
  action: >
    {{ ansible_pkg_mgr }} 
    name= "{{ item }}"
    state=present 
    update_cache=yes
  with_items:
    - expect
    - git
    - vim

- name: install system updates for centos systems
  yum: 
    name= "{{ item }}"
    state=latest 
    update_cache=yes
  with_items:
    - unzip
    - libselinux-python
    - openssl
    - nginx
  when: ansible_distribution == "CentOS"

- name: install system updates for ubuntu systems
  apt: upgrade=dist update_cache=yes
  when: ansible_distribution == "Ubuntu"  

- pip:
    name: pexpect
    
