Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64-juju"
  #vagrant plugin install vagrant-disksize
  config.disksize.size = '12GB'
  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     #Customize the amount of memory on the VM:
     #vb.memory = "256"
  end
  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-get install -y ansible
     sudo apt-get install -y snapd
     sudo snap install snapcraft --classic
     git clone https://github.com/vinayski/home.git home
     ln -sf home/.profile .profile
     ln -sf home/.functions .functions
    SHELL
end
