Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64-juju"
  #vagrant plugin install vagrant-disksize
  config.disksize.size = '10GB'
  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     #Customize the amount of memory on the VM:
     #vb.memory = "256"
  end
  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-get install -y ansible
     sudo apt-get install snapd
     sudo snap install snapcraft --classic
    SHELL
end
