---
- name: stoken
  apt:
    name: stoken

- pip:
    name: pexpect
    
- name: expect
  apt:
    name: expect

- name: Import Token
  expect: 
    command: stoken import --force --file=/vagrant/token.sdtid
    responses:
        (.*)word: \n

- name: vpnc
  apt:
    name: vpnc

- name: sshuttle
  apt:
    name: sshuttle

- name: git
  apt:
    name: git

- git:
    repo: 'https://github.com/vinayski/home.git'
    dest: /home/vagrant/home

    
- file:
    src: '/home/vagrant/home/{{ item.src }}'
    dest: '/home/vagrant/{{ item.src }}'
    state: link    
    force: yes
    mode: 0700
  with_items:
    - { src: '.functions'}
    - { src: '.profile'}

- file:
    src: '/vagrant/{{ item.s }}'
    dest: '{{ item.d }}'
    state: link    
    force: yes
    mode: "u=rwx,g=rx,o=rx"
  with_items:
          - { s: 'vpnc.default' , d:'/etc/default/vpnc'}
          - { s: 'reconnect-script', d:'/etc/vpnc/reconnect-script'}
          - { s: 'vpnc-script-disconnect-action', d:'/etc/vpnc/vpnc-script-disconnect-action'}
          - { s: 'vpnc', d:'/etc/init.d/vpnc'}
