---
- name: stoken
  apt:
    name: stoken

- pip:
    name: pexpect
    
- name: expect
  apt:
    name: expect

- name: Import Token
  expect: 
    command: stoken import --force --file=/vagrant/token.sdtid
    responses:
        (.*)word: \n

- name: vpnc
  apt:
    name: vpnc

- name: sshuttle
  apt:
    name: sshuttle

- name: git
  apt:
    name: git

- git:
    repo: 'https://github.com/vinayski/home.git'
    dest: /home/vagrant/home

    
- file:
    src: '/home/vagrant/home/{{ item.src }}'
    dest: '/home/vagrant/{{ item.src }}'
    state: link    
    force: yes
  with_items:
    - { src: '.functions'}
    - { src: '.profile'}


