---
- name: add pub key
  shell: echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDU/rdD2WgoaSVm2e4ZtqMU+U1m5DqemcrI41bXfi+5T4aXS5j0/cxwkxYmWUy/eyDOo0YVyFdSK9jCClENVnvl2JGJro4YiBdC1Acd/4XHrhgyWXKgXAGHq92K4j+AXZgm3g6Bl/LuoB7OhYPi8cte4gtTkk++SEuJGsTGXaQI2OXcaH3u4l4mikG92CfzC+3ERFZibeHiLYQMhb0NIY8Pp5nLRXGsYrvjKmhFUMk4yBSKacou2rRT5GQpzvWKG8O3NqYhk/YKivD92qbFBwM6X5vDl+7SbHMCGdunSJ5iL9t99dXJj7W+s6zxSnr9HKvHCbEfkOPxIR/U+M3IUMan" > /home/vagrant/.ssh/authorized_keys

- name: install basic package using {{ ansible_pkg_mgr }}
  action: >
    {{ ansible_pkg_mgr }} 
    name= "{{ item }}"
    state=present 
    update_cache=yes
    install_recommends=no
  with_items:
    - expect
    - git
    - vim
    - python

- name: install system updates for {{ ansible_distribution }} 
  apt: 
    upgrade: no 
    update_cache: yes
  when: ansible_distribution == "Debian"  

- name: install basic package using apt
  apt: 
    name: "{{ item }}"
    state: latest
    update_cache: yes
    install_recommends: yes
  with_items:
    - expect
    - git
    - vim
    - python
    - python-pip
  when: ansible_distribution == "Debian"

- name: install git
  apt: 
    name: git
    state: latest
    update_cache: yes
    install_recommends: yes
  when: ansible_distribution == "Debian"

- name: install system updates for centos systems
  yum: 
    name: "{{ item }}"
    state: latest 
    update_cache: yes
  with_items:
    - unzip
    - libselinux-python
    - openssl
    - nginx
  when: ansible_distribution == "CentOS"

- pip: 
   name: pexpect 
