# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #config.vm.box = "centos/7"
  #config.vm.box = "generic/alpine36"
  #config.vm.box = "generic/centos7"
  #config.vm.box = "generic/ubuntu1604"
  #config.vm.box = "hashicorp/precise64"
  #config.vm.box = "bento/ubuntu-16.04"
  #config.vm.box = "simoncrook/boot2docker"
  config.vm.box = "laravel/homestead"
  config.vm.provider "hyperv"
  config.vm.network "public_network"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "hyperv" do |h|
    h.memory = "512"
    h.enable_virtualization_extensions = true
    #h.differencing_disk = true
  end

  config.vm.provision "shell", inline: <<-SHELL
    #echo "%_query_all_fmt %%{name}-%%{version}-%%{release}.%%{arch}" >> ~/.rpmmacros
    #yum update
    #yum install epel-release
    #yum install ansible
    #sudo add-apt-repository ppa:jonathonf/python-3.6
    #sudo apt-get update
    #sudo apt-get -y install python3.6
    #sudo apt-get -y install python-pip python-dev build-essential 
    #sudo pip install --upgrade pip
    #sudo apt-get -y install ansible
    SHELL
end
